-- Names from fake players addon https://github.com/C0nw0nk/Garrys-Mod-Fake-Players

D3bot.Names = {
 "3a4eM_MHE_Huk",
 "3a6bIJl_kAk_CpaTb",
 "noJIb3oBaTEJIb",
 "BECOMbIu_APryMEHT",
 "CTA9l_MYX",
 "HEHABU}-{Y_4YPok",
 "♡/\\IO60Bb-C-nepBoro-FRAGA♡",
 "PeMoHt_DoP0r",
 "3aTpoJIJIeH",
 "uc/7oBegb_/7ugopaca",
 "Y}-{E_HE_DEBCTBE(NICK)",
 "CTAPUKU_HE_CJIbILIJAT_BA$$",
 "MAMuHA_KyPTKA_JIe}I{uT_y_BPAr0B",
 "Bbl6ePu_K/\\aCC •nugopac",
 "aTJIaHT_Pa$/7paBuJI_/7eHuc",
 "Ha_Xy+o_Bep4y_3anyTaTb_Xo4y",
 "4BK_{$WAG}Hep",
 "mexaccKa9 /7u3ga 6eH3OeJlgou",
 "aHa/\\uTeK_TuTeK",
 "/7epe}|{uJI_a6op7",
 "y6uJI_ruTJIepa[repoú]",
 "RATтатуй_noDyDи_V_moy_ХXXYU",
 "BO$$_USLUGI.RU",
 "ТИРАН_O_ZAVR___SSSEEEXXX",
 "СYП_и3_сemи_3aLOOP",
 "=BbE6aJlC9l.B.6awHu.6Jlu3HEŲbl=",
 "cJlblwb_6blk_Te6e_kup∆blk",
 "Кu$$/\\ble_Cu$$bku",
 "IIoXuTuTeJLb_geTuWek1992",
 "JI+o6iTEJIb_EkCTPEMizMA",
 "KaHHubaJl_KoJlJlekToP",
 ".:PA100MAH4UK:.",
 "5/2_HA_CS_OFFICE<3a/\\o}|{HuK>",
 "He. K/\\l-OeT.Huxy9l",
 "TaM_rge_B39l/\\_y}l{e_HeT",
 "/7oBblLLleH_go_y36eKa",
 "TTpowy_npocTuTb_ecJlu_TpaxHyJl",
 "/7upo}|{oK_c_XaeLLIKoú",
 "CEMEH_Ho_He_CnepMa",
 "UNITED_SEXY_GOYS (✡︎)",
 "ue3apb-Pa3geBaû-u-TpaxcTByû",
 "MEN9l_KA3H9lT(((",
 "npucTyn_xuxukapguuXD",
 "シ xuXaHbKu ga XaXaHbKu ټ",
 "B go6peHbKoM 3gPaBuu ٩(̾●̮̮̃̾•̃̾)۶",
 "_AM6u[DEXTER]_C_6epemaMu_",
 "C6OP_xYpMbl",
 "9l_OcJlE/7_6Jl9999Tb...!",
 "y_M3H9I_3cTb_6yTEP6poT",
 "u_npo_cTapyxy_6blBaeT_nopHyxa",
 "gpo4u~MHE~\\/~TeMHoTe",
 "npuKoJla_TESLA",
 "5_6YTblJlok_BoDkU",
 "3APY6/\\IO_TOnOPOM_CYKA",
 "3eJleHblU_CJloHiK",
 "٠•○๑۩ ╬ E6AL VaS GoSpOdA ╬ ۩๑○•٠",
 "yūDu_HAXyū",
 "Tpyn_6a6ylIlku....",
 "ka3Hb_gara_u_Tag)+(uka",
 "paJIA4_hA4eú(v.l.a.d.)",
 "XYUTA_BALLI_CEPBEP",
 "SaDDaM_XyũBceM",
 "CapamoBckuú_kapameJlb",
 "AHmuCeMum[YHWH]",
 "%awucm 1.4.8.8",
 "Tpycbl_B_ropoLLIeK",
 "Cka3o4Ha9l_TTepcoHa",
 "BTopIIIeHue_B_CPAkoTaH",
 "He_ybNBaNTE_CPA3y",
 "Cu6upckoe He4to",
 "4e_y6era/\\ _a_4e_goroHl9/\\u? [666MYCOPA_6/\\9lgu666]",
 "4eCHo4ok",
 "ABORT_Deagle'om",
 "DByXCoTbIū...",
 "3akPbIJl_DoJlru",
 "BoT_Te6e_Ho}l{...",
 "MHe_3geCb_cTPalIlHo",
 "rocnogu npocTu",
 "6ecnoHToBbIū_nuPo)I(ok",
 "He_Bblpe3aHo_He_nepekogupoBaHo",
 "BceM_C4aCTb9l_3gopoBb9l",
 "nepe}|{uJl_gBa_CyuUuga",
 "kAkA9l_Heo}|{UDaHHocTb",
 "6o}|{e_Moū_OHu_noBc+oDy",
 "roplIlo4ek_C_XuXuXu)))",
 "Daū_noueJly+o",
 "XPUCTOC_BOCKPEC",
 "TECAK_BOCKPEC",
 "yroJIoBHblū_PO3blCK",
 "JIeXa_TeJlek_Cnu3DoXaJI",
 "LLIaPMaHkA_3aBeDeHa...",
 "CEkC_no_CkuDke",
 "Ya_3aPe3aJl_ubIrAHa",
 "TuLLIe_y36eku_Cn9IT",
 "25cm_B_XoJloDHoū_BoDe",
 "KryToū_nEPeu",
 "9l_JlOMAAAAJl_CTEKJlOOOOO :DDDD",
 "冂囗山仨几_廾丹乂丫认",
 "MaCTyP6Ek",
 "JlukBuDaToP",
 "kPoBaBblû_Pe}I{uM",
 "Д }|{ O ]-[ Y И ]{",
 "CTaPoCTb",
 "3akoHHonoCJlyLLIHbIú_rpa}|{DaHuH",
 "BcErO_JIulIlb_npocToú_CoBeTCkuú...",
 "LetsPlay_no_MeinKampfy",
 "AHAHAC HA CTOJIE",
 "T P A B O K Y P",
 "E6ALLIy_B_kALLIy",
 "yCTAJl_DpO4uTb",
 "/7o4TaJlboH_%JleLLlkuH",
 "Pablo_PacKyMaP",
 "He_TBoū_yPoBeHb_goPorOū",
 "9l_BCE_PABHO_6yDy_CPATb",
 "$$_300''KILL'o'GraMGovnA''300_$$",
 "BOCKPEC_U_PA3HEC_/7A6JIUK",
 "4uTaIO_CTuXu_/7poCTuTyTkAM",
 "Ha_ToM_U_CorPELLIuJlu...",
 "CuCbku_uJlu_}|{O/7A? (DylIla6paT...)",
 "эHepruя koTa 6oPuCa",
 "4to_CoCyT_4eMnuoHbI????",
 "JIIO6iTEJIb_RYTP (CAC AXAXAX)",
 "}|{EPTBA_DoMaLLlHeGo_BaCuJlu9I",
 "XPEHOPE3KA",
 "†7/oJleT9lT_E6aJlbHu4ku†",
 "KpuMuHaJlbHblū_EJIE(MEHT)",
 "KOT B CMETAHE",
 "KOPOJIb_U_LLlyT",
 "uHTepeCHa9_JIu4HocTb",
 "廾🝗⺁尸⺎и具ㄖ尸闩⼕ы",
 "LLIAC TTU3DAHET",
 "/7o_CyTu_LEG3ND@ *__*",
 "zalupavrot88",
 "3DPABCTBYUTE_/7UDOPACTBYUTE",
 "C/7A3M_C%UHKTEPA",
 "HAD3UPATEJlb_KOHuJIAGEP9I",
 "Tapochek.net_A_kyDa_nponaJlu?",
 "kABkA3Ckuú +PE3OHAHC+",
 "AGENT 47 (XPOMOCOM)",
 "MEH9I CJIblLLIHO???",
 "BoDuTeJIb napoBo3ukA...",
 "UBAH HAMA3",
 "E6ALLIY_DETEU",
 "Xa4u_B_TTe4u (uDu noDpo4u)",
 "DJ Holocaust",
 "TTePeCTpEJIkA 3uraMu",
 "CB9TOú OTEu",
 "Te6e TTu3Deu",
 "ODHOXyūCTBEHHO",
 "APEHDA_TTU3DbI",
 "CTTACU U COXPAHU",
 "CMoTPuTeJIb B GJIoPuXoJIbI",
 "TyDbIM Cl0DbIM...",
 "rpoMuJI JIaPek TaD}|{ukOB",
 "/7PeDcTABuTeJIb_rPynnbI_JIEC",
 "9I Xyú BoTkHy u nPoBePHy...",
 "ka}|{DoMy B POT HaDaBaJI",
 "4eJIoBek_C_3uGoú_B_KAPMAHE",
 "repoú_kBePxy_DbIPoú",
 "Be3DeCCyLLIuû",
 "%uHT~Xy9Mu",
 "APTYP_U_/7ugapMoTbl",
 "CE3oH_Puca",
 "TyT Mo}|{Ho DpO4uTb nunuHDpyC???",
 "GRAF_TRAXYLA",
 "Ho4b_So4nbIX_xYúu0B",
 "Dpo4uTe_MHe_BCEM_CEPBEPOM",
 "E6y_Do_CJIE3",
 "9I Paccka}|{y Te6e Cka3ky",
 "ВеСё/\\blU_Таk0ū",
 "D }|{ E K TT O T (Xyû Te B PoT)",
 "9|_6ery_a_BoJIoCbI_Ha3aD",
 "Fan Club Uucyca XpucTa",
 "_HeO_ -yBepHyJIc9I oT XyeB-",
 "KaPTbI DeHbru DBa Xy9",
 "nolIleJIecTuTe MHe 3a OkHoM",
 "aHreJI_XopoHuTeJIb",
 "}|{AH KJIOD B POT 6PAJI",
 "XuXuKa+0LLIuû DokToP",
 "HaXuXuKaJI Ha Cpok",
 "CoCok_B_HoCoK",
 "KaPaTeJIb MeHbLLIuHcTB",
 "kaHucTpA_C_6eH3uHoM",
 "koJI9H u3HaCuJIoBaJI AHAHAC",
 "He_cMeLLlHo",
 "CoBepLLIeHHbIe_CuCbKu 18+",
 "CeKc_/7o_DoMo%oHy",
 "cMepTb B HuLLIuTe",
 "pennep_C9BA",
 "6oDp9I4koM_HaXyú",
 "Xa4_C_PbIHkA_Ha_cs_italy",
 "nJI9cKu_XyeTp9cKu",
 "e6aJIo_KaHHu6a/\\a",
 "Cu6uPcKuū_MaCTyP6aToP",
 "cMelIluHkA_B_PoT_nonaJIa)))))))",
 "CbIH_%ePMePa",
 "XJle6o6yJlo4HoE_UzDeJluE",
 "TAK_6bIBaeT",
 "rapuK_XyúJIo_XaPJIaMoB",
 "BOT_OHO_HA_XyIO_HAMOTAHO",
 ")|(u3Hb_nocJIe_Ka3Hu",
 "MoTbIJIЁK",
 "DJ Блокnote",
 "DpO4y u XAXA4y",
 "nocpamb_3a_60_cekyHg [Muccu9l_HeBblnoJIHuMa]",
 "o/7epaTop-[/\\/\\e%e]gpoHa",
 "DpO4y_no_PaCnuCaHuIO",
 "SтaРа9I_Cyka_S_K0sоYú",
 "OHu UDyT",
 "Ha_4To_Ya_TpA4y_BPEM9...",
 "He_6oJIee_4eM_Ha6JI|ODaTeJIb",
 "ГaHC_XpuCTuaH_TTeHuC",
 "yMoTToDpo4uTeJIbHo",
 "Doxy9l_4ego_y3HaJI",
 "BPEMEHHbIE_TPYDHOCTU...",
 "Bpar_GoCyDAPCTBA",
 "BcE_MeH9_DaBHo_TTocJIaJIu_HaXyú...",
 "HaTeJIbHbIû_KPECTUK",
 "C4aCTbe_6JI9Tb_B_Moeú_CyDb6e...",
 "no3akpblBaJIu_nu3Daku",
 "noCukyH4uk_C_KpA6oM",
 "MO)|(EM TTODPO4UTb (1941-1945)",
 "Я_noMHю_6eлbIe_o6ou...",
 "ADMUHUCTPATOP CEPBEPA",
 "KoHckuú }|{ona Pa3PblBaTeJlb",
 "yMoPuTeJIbHo xD",
 "CBUHOПAC",
 "BOT_ЭTO_TTPUKOOOOOЛ :DDD",
 "Bop_B_3anoe",
 "%ecTuBa/\\b_XyёB",
 "6e3yMHbIû_}|{uD",
 "6eckoHe4Hoe_LeTo (u Ap6aLeTbI)",
 "rappu nuDoP u y3Huk KoHcJIarep9l",
 "ADCKИЙ DPOЧИJIA",
 "6yDb_TbI_nPokJI9T_neppu_XyeSoS",
 "ona4upuk!",
 "uPkyTcKue_MoJIoTo4HuKu)))))",
 "noMeH9JI_rpexu_Ha_XuXu"
}